services:
  - type: web
    name: hostel-management-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://hostel-management-backend.onrender.com  # Replace with your actual backend URL after deployment
      - key: NODE_VERSION
        value: 18.x
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free
    autoDeploy: true
